name: Checkver on app manifests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_manifest_updates:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install scoop
        shell: powershell
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex

      - name: Run checkver
        shell: powershell
        run: |
          $scoop_path = scoop prefix scoop
          $checkver_path = $scoop_path + "\bin\checkver.ps1"
          $args = "-Dir ./bucket -Update"

          $cmd = $checkver_path + $args
          iex $cmd
      
      - uses: EndBug/add-and-commit@v5
        with:
          message: "Bot: Daily manifest update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}